/**
 * RASQ Upper-Limb Motor Screen — Seated Elbow Extension Toward Target and Return.
 *
 * A pure, command-driven reducer. Independent of forward-reach-engine.ts and
 * lateral-reach-engine.ts — no shared module, no imported private logic, no
 * refactor of either reach engine. No UI dependency, no Session Orchestrator
 * dependency, no interactive-shoulder state-machine reuse.
 *
 * Three concerns are kept separate:
 *
 * A. Wrist target-task measurement — movement onset, target entry, dwell,
 *    return, timing, and wrist path metrics. Wrist tracking controls event
 *    continuity and protective pauses.
 *
 * B. Optional factual 2D elbow-angle observation — peakElbowExtensionDeg is
 *    populated only when the tested-side shoulder, elbow, and wrist are
 *    simultaneously valid and confident during outbound/dwelling. Angle
 *    availability never controls wrist-task completion. Shoulder or elbow
 *    loss does not open a protective pause while wrist tracking remains valid.
 *
 * C. Clinician interpretation — never generated by this engine.
 *
 * peakElbowExtensionDeg meaning (Phase 1 contract field, not renamed here):
 * Maximum observed 2D interior angle at the tested-side elbow, computed from
 * shoulder–elbow–wrist landmarks. This is not anatomical ROM, confirmation of
 * full extension, strength, spasticity, or impairment. Target reach is not
 * proof that anatomical elbow extension occurred.
 *
 * Composition only: distanceNormalized/isWristInsideTarget (target-hit.ts),
 * computeJointAngleDegrees/isJointConfident (motion-intelligence),
 * evaluateProtectivePause (protective-pause-evaluator.ts), and Phase 1
 * types/guards (types.ts) are imported read-only.
 *
 * Engine clock: monotonic lastAcceptedNowMs across all command types; frame
 * commands additionally require strictly increasing timestamps
 * (lastAcceptedFrameNowMs). No numeric threshold is hardcoded; every
 * threshold is required explicit configuration marked needs CV validation /
 * needs device testing / needs capture-data calibration below.
 */

import {
  computeJointAngleDegrees,
  isJointConfident,
  type JointId,
  type NormalizedMotionFrame,
} from "@/app/lib/motion-intelligence";
import { distanceNormalized, isWristInsideTarget } from "@/app/lib/interactive-shoulder/target-hit";
import type { NormalizedPoint } from "@/app/lib/interactive-shoulder/types";
import { evaluateProtectivePause } from "./protective-pause-evaluator";
import {
  isCompletionStateConsistentWithEvents,
  isRecord,
  isValidProtectivePauseResumeActor,
  isValidUpperLimbSide,
  validateUpperLimbMotorScreenSessionResultSafety,
  type ClinicalStopEvent,
  type ProtectivePauseEvent,
  type ProtectivePauseReason,
  type UpperLimbAttemptCompletionState,
  type UpperLimbMovementAttemptResult,
  type UpperLimbSide,
} from "./types";

// ---------------------------------------------------------------------------
// Tested-side joint resolution — local, exhaustive, no fallback.
// ---------------------------------------------------------------------------

const TESTED_SIDE_WRIST_JOINT_ID: Record<UpperLimbSide, JointId> = {
  left: "left_wrist",
  right: "right_wrist",
};

const TESTED_SIDE_ELBOW_JOINT_ID: Record<UpperLimbSide, JointId> = {
  left: "left_elbow",
  right: "right_elbow",
};

const TESTED_SIDE_SHOULDER_JOINT_ID: Record<UpperLimbSide, JointId> = {
  left: "left_shoulder",
  right: "right_shoulder",
};

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

export type ElbowExtensionZone = {
  point: NormalizedPoint;
  radius: number;
};

function isFiniteUnitCoordinate(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 1;
}

function isPositiveFiniteRadius(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value > 0;
}

type ZoneValidationResult =
  | { ok: true; zone: ElbowExtensionZone }
  | { ok: false; reason: "invalid_zone_geometry"; detail: string };

function validateZone(candidate: unknown, label: string): ZoneValidationResult {
  if (!isRecord(candidate)) {
    return { ok: false, reason: "invalid_zone_geometry", detail: `${label} must be an object` };
  }
  const point = candidate.point;
  if (!isRecord(point) || !isFiniteUnitCoordinate(point.x) || !isFiniteUnitCoordinate(point.y)) {
    return {
      ok: false,
      reason: "invalid_zone_geometry",
      detail: `${label}.point requires finite x and y within [0,1]`,
    };
  }
  if (!isPositiveFiniteRadius(candidate.radius)) {
    return { ok: false, reason: "invalid_zone_geometry", detail: `${label}.radius must be finite and > 0` };
  }
  return { ok: true, zone: { point: { x: point.x, y: point.y }, radius: candidate.radius } };
}

/** Circles touching or overlapping are rejected — a structural geometric rule, not a clinical threshold. */
function zonesOverlapOrTouch(a: ElbowExtensionZone, b: ElbowExtensionZone): boolean {
  return distanceNormalized(a.point, b.point) <= a.radius + b.radius;
}

type UnitDirection2D = { readonly x: number; readonly y: number };

/** Screen-space unit vector from starting zone center toward the fixed target — not anatomical placement. */
function computeNormalizedTargetDirection(
  startingZone: ElbowExtensionZone,
  fixedTarget: ElbowExtensionZone,
): UnitDirection2D | null {
  const dx = fixedTarget.point.x - startingZone.point.x;
  const dy = fixedTarget.point.y - startingZone.point.y;
  const magnitude = Math.hypot(dx, dy);
  if (magnitude === 0) return null;
  return { x: dx / magnitude, y: dy / magnitude };
}

function displacementFromStartCenter(wrist: NormalizedPoint, startCenter: NormalizedPoint): { x: number; y: number } {
  return { x: wrist.x - startCenter.x, y: wrist.y - startCenter.y };
}

function dot2(a: { x: number; y: number }, b: UnitDirection2D): number {
  return a.x * b.x + a.y * b.y;
}

/** Target-facing onset qualification — screen-space projection along configured target direction. */
function hasTargetFacingOnsetQualification(
  wrist: NormalizedPoint,
  startingZone: ElbowExtensionZone,
  normalizedTargetDirection: UnitDirection2D,
): boolean {
  const displacement = displacementFromStartCenter(wrist, startingZone.point);
  return dot2(displacement, normalizedTargetDirection) > startingZone.radius;
}

/** Non-target-facing side exit — screen-space projection opposite configured target direction. */
function hasWrongDirectionExit(
  wrist: NormalizedPoint,
  startingZone: ElbowExtensionZone,
  normalizedTargetDirection: UnitDirection2D,
): boolean {
  const displacement = displacementFromStartCenter(wrist, startingZone.point);
  return dot2(displacement, normalizedTargetDirection) < -startingZone.radius;
}

function cloneElbowExtensionConfig(config: ElbowExtensionConfig): ElbowExtensionConfig {
  return {
    testedSide: config.testedSide,
    fixedTarget: {
      point: { x: config.fixedTarget.point.x, y: config.fixedTarget.point.y },
      radius: config.fixedTarget.radius,
    },
    startingZone: {
      point: { x: config.startingZone.point.x, y: config.startingZone.point.y },
      radius: config.startingZone.radius,
    },
    tracking: {
      minWristVisibility: config.tracking.minWristVisibility,
      maxAllowedGapMs: config.tracking.maxAllowedGapMs,
      minShoulderVisibility: config.tracking.minShoulderVisibility,
      minElbowVisibility: config.tracking.minElbowVisibility,
    },
    timing: {
      onsetConfirmationMs: config.timing.onsetConfirmationMs,
      dwellDurationMs: config.timing.dwellDurationMs,
      returnConfirmationMs: config.timing.returnConfirmationMs,
    },
    normalizedTargetDirection: {
      x: config.normalizedTargetDirection.x,
      y: config.normalizedTargetDirection.y,
    },
  };
}

// ---------------------------------------------------------------------------
// Configuration — explicit, no internal defaults, no invented values.
// ---------------------------------------------------------------------------

export type ElbowExtensionTrackingConfig = {
  /** needs CV validation, needs device testing. */
  minWristVisibility: number;
  /** needs CV validation, needs device testing. */
  maxAllowedGapMs: number;
  /** needs CV validation, needs device testing — optional angle metric only. */
  minShoulderVisibility: number;
  /** needs CV validation, needs device testing — optional angle metric only. */
  minElbowVisibility: number;
};

export type ElbowExtensionTimingConfig = {
  /** needs CV validation, needs capture-data calibration. */
  onsetConfirmationMs: number;
  /** needs CV validation, needs capture-data calibration. */
  dwellDurationMs: number;
  /** needs CV validation, needs capture-data calibration. */
  returnConfirmationMs: number;
};

export type ElbowExtensionConfig = {
  testedSide: UpperLimbSide;
  fixedTarget: ElbowExtensionZone;
  startingZone: ElbowExtensionZone;
  tracking: ElbowExtensionTrackingConfig;
  timing: ElbowExtensionTimingConfig;
  /**
   * Derived once, at validation time, from
   * normalize(fixedTarget.point - startingZone.point). Never a clinical or
   * anatomical claim — a plain screen-space unit vector used only to gate
   * target-facing onset confirmation.
   */
  readonly normalizedTargetDirection: UnitDirection2D;
};

export type ElbowExtensionConfigValidationFailure =
  | "invalid_config"
  | "invalid_tested_side"
  | "invalid_zone_geometry"
  | "zones_overlap"
  | "ambiguous_target_direction"
  | "invalid_tracking_config"
  | "invalid_timing_config";

export type ElbowExtensionConfigValidationResult =
  | { ok: true; config: ElbowExtensionConfig }
  | { ok: false; reason: ElbowExtensionConfigValidationFailure; detail?: string };

function validateVisibilityField(
  value: unknown,
  label: string,
): { ok: true; value: number } | { ok: false; reason: "invalid_tracking_config"; detail: string } {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > 1) {
    return {
      ok: false,
      reason: "invalid_tracking_config",
      detail: `${label} must be a finite number within [0,1]`,
    };
  }
  return { ok: true, value };
}

function validateTrackingConfig(
  candidate: unknown,
):
  | { ok: true; tracking: ElbowExtensionTrackingConfig }
  | { ok: false; reason: "invalid_tracking_config"; detail: string } {
  if (!isRecord(candidate)) {
    return { ok: false, reason: "invalid_tracking_config", detail: "tracking config must be an object" };
  }
  const wristVis = validateVisibilityField(candidate.minWristVisibility, "minWristVisibility");
  if (!wristVis.ok) return wristVis;
  const shoulderVis = validateVisibilityField(candidate.minShoulderVisibility, "minShoulderVisibility");
  if (!shoulderVis.ok) return shoulderVis;
  const elbowVis = validateVisibilityField(candidate.minElbowVisibility, "minElbowVisibility");
  if (!elbowVis.ok) return elbowVis;
  if (
    typeof candidate.maxAllowedGapMs !== "number" ||
    !Number.isFinite(candidate.maxAllowedGapMs) ||
    candidate.maxAllowedGapMs < 0
  ) {
    return {
      ok: false,
      reason: "invalid_tracking_config",
      detail: "maxAllowedGapMs must be a finite number >= 0",
    };
  }
  return {
    ok: true,
    tracking: {
      minWristVisibility: wristVis.value,
      maxAllowedGapMs: candidate.maxAllowedGapMs,
      minShoulderVisibility: shoulderVis.value,
      minElbowVisibility: elbowVis.value,
    },
  };
}

function validateTimingConfig(
  candidate: unknown,
): { ok: true; timing: ElbowExtensionTimingConfig } | { ok: false; reason: "invalid_timing_config"; detail: string } {
  if (!isRecord(candidate)) {
    return { ok: false, reason: "invalid_timing_config", detail: "timing config must be an object" };
  }
  const fields = ["onsetConfirmationMs", "dwellDurationMs", "returnConfirmationMs"] as const;
  for (const field of fields) {
    const value = candidate[field];
    if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
      return {
        ok: false,
        reason: "invalid_timing_config",
        detail: `${field} must be a finite number >= 0`,
      };
    }
  }
  return {
    ok: true,
    timing: {
      onsetConfirmationMs: candidate.onsetConfirmationMs as number,
      dwellDurationMs: candidate.dwellDurationMs as number,
      returnConfirmationMs: candidate.returnConfirmationMs as number,
    },
  };
}

export function validateElbowExtensionConfig(candidate: unknown): ElbowExtensionConfigValidationResult {
  if (!isRecord(candidate)) {
    return { ok: false, reason: "invalid_config", detail: "config must be an object" };
  }

  if (!isValidUpperLimbSide(candidate.testedSide)) {
    return { ok: false, reason: "invalid_tested_side" };
  }
  const testedSide = candidate.testedSide;

  const targetResult = validateZone(candidate.fixedTarget, "fixedTarget");
  if (!targetResult.ok) return targetResult;

  const startingZoneResult = validateZone(candidate.startingZone, "startingZone");
  if (!startingZoneResult.ok) return startingZoneResult;

  if (zonesOverlapOrTouch(targetResult.zone, startingZoneResult.zone)) {
    return { ok: false, reason: "zones_overlap" };
  }

  const normalizedTargetDirection = computeNormalizedTargetDirection(startingZoneResult.zone, targetResult.zone);
  if (normalizedTargetDirection === null) {
    return { ok: false, reason: "ambiguous_target_direction" };
  }

  const trackingResult = validateTrackingConfig(candidate.tracking);
  if (!trackingResult.ok) return trackingResult;

  const timingResult = validateTimingConfig(candidate.timing);
  if (!timingResult.ok) return timingResult;

  return {
    ok: true,
    config: cloneElbowExtensionConfig({
      testedSide,
      fixedTarget: targetResult.zone,
      startingZone: startingZoneResult.zone,
      tracking: trackingResult.tracking,
      timing: timingResult.timing,
      normalizedTargetDirection,
    }),
  };
}

// ---------------------------------------------------------------------------
// Internal runtime phases
// ---------------------------------------------------------------------------

export const ELBOW_EXTENSION_PHASES = [
  "idle",
  "awaiting_readiness",
  "ready_confirmed_awaiting_onset",
  "outbound",
  "dwelling",
  "reach_confirmed",
  "returning",
  "completed_pending_finalization",
] as const;
export type ElbowExtensionPhase = (typeof ELBOW_EXTENSION_PHASES)[number];

export type ElbowExtensionActivePause = {
  reason: ProtectivePauseReason;
  startedAtMs: number;
};

type TimedCandidate = { candidateStartedAtMs: number };

type DwellCandidate = {
  candidateStartedAtMs: number;
  outboundSamplesAtEntry: NormalizedPoint[];
};

type ElbowExtensionAttemptStateInternal = {
  readonly config: ElbowExtensionConfig;
  readonly attemptIndex: number;
  readonly armedAtMs: number;

  lastAcceptedNowMs: number;
  lastAcceptedFrameNowMs: number | null;

  phase: ElbowExtensionPhase;
  terminal: boolean;
  activePause: ElbowExtensionActivePause | null;

  lastValidWristSample: { point: NormalizedPoint; atMs: number } | null;
  invalidTrackingSinceMs: number | null;

  onsetCandidate: TimedCandidate | null;
  pendingOnsetSamples: NormalizedPoint[];
  pendingTargetEntryAtMs: number | null;
  nonTargetFacingExitObservedBeforeValidOnset: boolean;
  dwellCandidate: DwellCandidate | null;
  returnCandidate: TimedCandidate | null;

  movementOnsetAtMs: number | null;
  movementOnsetWristPoint: NormalizedPoint | null;
  outboundSamples: NormalizedPoint[];
  outboundIntegrityBroken: boolean;

  targetEntryAtMs: number | null;
  targetReachedFlag: boolean;
  reachConfirmedAtMs: number | null;
  dwellConfirmedFlag: boolean;

  returnConfirmedAtMs: number | null;
  returnToStartCompletedFlag: boolean;

  /** Running max observed 2D elbow angle during outbound/dwelling only. */
  peakElbowExtensionDegRunning: number | null;
  hadValidElbowAngleSample: boolean;

  completedAtMs: number | null;
  clinicalStopEvent: ClinicalStopEvent | null;
  runtimeInterruptionOccurred: boolean;
  notAssessableReason: string | null;

  protectivePauseEvents: ProtectivePauseEvent[];

  finalResult: UpperLimbMovementAttemptResult | null;
};

export type ElbowExtensionAttemptState = ElbowExtensionAttemptStateInternal;

export type ElbowExtensionAttemptInitializationFailure = "invalid_armed_at_ms" | "invalid_attempt_index";

export type ElbowExtensionAttemptInitializationResult =
  | { ok: true; state: ElbowExtensionAttemptState }
  | { ok: false; reason: ElbowExtensionAttemptInitializationFailure };

export function createElbowExtensionAttemptState(
  config: ElbowExtensionConfig,
  attemptIndex: number,
  armedAtMs: number,
): ElbowExtensionAttemptInitializationResult {
  if (!Number.isFinite(armedAtMs) || armedAtMs < 0) {
    return { ok: false, reason: "invalid_armed_at_ms" };
  }
  if (!Number.isFinite(attemptIndex)) {
    return { ok: false, reason: "invalid_attempt_index" };
  }
  return {
    ok: true,
    state: {
      config: cloneElbowExtensionConfig(config),
      attemptIndex,
      armedAtMs,
      lastAcceptedNowMs: armedAtMs,
      lastAcceptedFrameNowMs: null,
      phase: "idle",
      terminal: false,
      activePause: null,
      lastValidWristSample: null,
      invalidTrackingSinceMs: null,
      onsetCandidate: null,
      pendingOnsetSamples: [],
      pendingTargetEntryAtMs: null,
      nonTargetFacingExitObservedBeforeValidOnset: false,
      dwellCandidate: null,
      returnCandidate: null,
      movementOnsetAtMs: null,
      movementOnsetWristPoint: null,
      outboundSamples: [],
      outboundIntegrityBroken: false,
      targetEntryAtMs: null,
      targetReachedFlag: false,
      reachConfirmedAtMs: null,
      dwellConfirmedFlag: false,
      returnConfirmedAtMs: null,
      returnToStartCompletedFlag: false,
      peakElbowExtensionDegRunning: null,
      hadValidElbowAngleSample: false,
      completedAtMs: null,
      clinicalStopEvent: null,
      runtimeInterruptionOccurred: false,
      notAssessableReason: null,
      protectivePauseEvents: [],
      finalResult: null,
    },
  };
}

export type ElbowExtensionRuntimeSnapshot = {
  attemptIndex: number;
  phase: ElbowExtensionPhase;
  terminal: boolean;
  hasActivePause: boolean;
  targetReached: boolean;
  dwellConfirmed: boolean;
  returnToStartCompleted: boolean;
  protectivePauseCount: number;
};

export function getElbowExtensionRuntimeSnapshot(state: ElbowExtensionAttemptState): ElbowExtensionRuntimeSnapshot {
  return {
    attemptIndex: state.attemptIndex,
    phase: state.phase,
    terminal: state.terminal,
    hasActivePause: state.activePause !== null,
    targetReached: state.targetReachedFlag,
    dwellConfirmed: state.dwellConfirmedFlag,
    returnToStartCompleted: state.returnToStartCompletedFlag,
    protectivePauseCount: state.protectivePauseEvents.length,
  };
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

export type ElbowExtensionCommand =
  | { type: "frame"; nowMs: number; frame: NormalizedMotionFrame }
  | { type: "observationUnavailable"; nowMs: number }
  | { type: "readinessConfirmed"; nowMs: number; confirmedBy: unknown }
  | { type: "resumeRequested"; nowMs: number; readinessConfirmedAt: unknown; resumedBy: unknown }
  | { type: "clinicalStopReceived"; nowMs: number; event: ClinicalStopEvent }
  | { type: "runtimeInterruptionReceived"; nowMs: number; reason?: string }
  | { type: "attemptWindowEnded"; nowMs: number }
  | { type: "markedNotAssessable"; nowMs: number; reason: string };

export type ElbowExtensionCommandRejectionReason =
  | "attempt_already_terminal"
  | "invalid_now_ms"
  | "now_ms_not_monotonic"
  | "frame_timestamp_not_strictly_increasing"
  | "awaiting_explicit_finalization"
  | "readiness_not_applicable_in_current_phase"
  | "readiness_requires_wrist_in_starting_zone"
  | "readiness_requires_valid_confirmed_by"
  | "no_active_pause_to_resume"
  | "resume_requires_readiness_confirmation"
  | "resume_requires_valid_human_actor";

export type ElbowExtensionCommandResult =
  | {
      status: "applied";
      state: ElbowExtensionAttemptState;
      snapshot: ElbowExtensionRuntimeSnapshot;
      protectivePauseEvent: ProtectivePauseEvent | null;
      attemptResult: UpperLimbMovementAttemptResult | null;
    }
  | {
      status: "rejected";
      reason: ElbowExtensionCommandRejectionReason;
      state: ElbowExtensionAttemptState;
      snapshot: ElbowExtensionRuntimeSnapshot;
    };

function applied(
  state: ElbowExtensionAttemptState,
  protectivePauseEvent: ProtectivePauseEvent | null = null,
  attemptResult: UpperLimbMovementAttemptResult | null = null,
): ElbowExtensionCommandResult {
  return {
    status: "applied",
    state,
    snapshot: getElbowExtensionRuntimeSnapshot(state),
    protectivePauseEvent,
    attemptResult,
  };
}

function rejected(
  state: ElbowExtensionAttemptState,
  reason: ElbowExtensionCommandRejectionReason,
): ElbowExtensionCommandResult {
  return { status: "rejected", reason, state, snapshot: getElbowExtensionRuntimeSnapshot(state) };
}

function validateNowMs(
  lastAcceptedNowMs: number,
  nowMs: number,
): { ok: true } | { ok: false; reason: "invalid_now_ms" | "now_ms_not_monotonic" } {
  if (!Number.isFinite(nowMs) || nowMs < 0) return { ok: false, reason: "invalid_now_ms" };
  if (nowMs < lastAcceptedNowMs) return { ok: false, reason: "now_ms_not_monotonic" };
  return { ok: true };
}

function validateFrameNowMs(
  lastAcceptedFrameNowMs: number | null,
  nowMs: number,
): { ok: true } | { ok: false; reason: "invalid_now_ms" | "frame_timestamp_not_strictly_increasing" } {
  if (!Number.isFinite(nowMs) || nowMs < 0) return { ok: false, reason: "invalid_now_ms" };
  if (lastAcceptedFrameNowMs !== null && nowMs <= lastAcceptedFrameNowMs) {
    return { ok: false, reason: "frame_timestamp_not_strictly_increasing" };
  }
  return { ok: true };
}

// ---------------------------------------------------------------------------
// Wrist sample — controls event continuity and protective pauses.
// ---------------------------------------------------------------------------

function extractTestedSideWristSample(
  frame: NormalizedMotionFrame,
  config: ElbowExtensionConfig,
): NormalizedPoint | null {
  const jointId = TESTED_SIDE_WRIST_JOINT_ID[config.testedSide];
  const joint = frame.joints[jointId];
  if (!joint) return null;
  if (!isJointConfident(joint.confidence, config.tracking.minWristVisibility)) return null;
  const { x, y } = joint.landmark;
  if (!isFiniteUnitCoordinate(x) || !isFiniteUnitCoordinate(y)) return null;
  return { x, y };
}

// ---------------------------------------------------------------------------
// Optional 2D elbow-angle observation — never an event gate.
// ---------------------------------------------------------------------------

/**
 * Observed 2D interior angle at the tested-side elbow (shoulder→elbow→wrist).
 * Returns null when any required landmark is missing, out of bounds, or below
 * the configured visibility thresholds. Does not affect wrist-task phases.
 */
export function extractObserved2DElbowAngleDegrees(
  frame: NormalizedMotionFrame,
  config: ElbowExtensionConfig,
): number | null {
  const shoulderId = TESTED_SIDE_SHOULDER_JOINT_ID[config.testedSide];
  const elbowId = TESTED_SIDE_ELBOW_JOINT_ID[config.testedSide];
  const wristId = TESTED_SIDE_WRIST_JOINT_ID[config.testedSide];

  const shoulderJoint = frame.joints[shoulderId];
  const elbowJoint = frame.joints[elbowId];
  const wristJoint = frame.joints[wristId];

  if (!shoulderJoint || !elbowJoint || !wristJoint) return null;

  const { tracking } = config;
  if (
    !isJointConfident(shoulderJoint.confidence, tracking.minShoulderVisibility) ||
    !isJointConfident(elbowJoint.confidence, tracking.minElbowVisibility) ||
    !isJointConfident(wristJoint.confidence, tracking.minWristVisibility)
  ) {
    return null;
  }

  const shoulder = shoulderJoint.landmark;
  const elbow = elbowJoint.landmark;
  const wrist = wristJoint.landmark;

  if (
    !isFiniteUnitCoordinate(shoulder.x) ||
    !isFiniteUnitCoordinate(shoulder.y) ||
    !isFiniteUnitCoordinate(elbow.x) ||
    !isFiniteUnitCoordinate(elbow.y) ||
    !isFiniteUnitCoordinate(wrist.x) ||
    !isFiniteUnitCoordinate(wrist.y)
  ) {
    return null;
  }

  return computeJointAngleDegrees(shoulder, elbow, wrist, {
    confidences: [shoulderJoint.confidence, elbowJoint.confidence, wristJoint.confidence],
    minConfidence: 0,
  });
}

function observePeakElbowAngleIfApplicable(
  state: ElbowExtensionAttemptStateInternal,
  frame: NormalizedMotionFrame,
): ElbowExtensionAttemptStateInternal {
  if (state.phase !== "outbound" && state.phase !== "dwelling") {
    return state;
  }
  const angle = extractObserved2DElbowAngleDegrees(frame, state.config);
  if (angle === null) {
    return state;
  }
  const peak =
    state.peakElbowExtensionDegRunning === null
      ? angle
      : Math.max(state.peakElbowExtensionDegRunning, angle);
  return {
    ...state,
    peakElbowExtensionDegRunning: peak,
    hadValidElbowAngleSample: true,
  };
}

// ---------------------------------------------------------------------------
// Path metrics
// ---------------------------------------------------------------------------

const PATH_EFFICIENCY_TOLERANCE = 1e-6;

function computePathMetrics(state: ElbowExtensionAttemptStateInternal): {
  normalizedPathLength: number | null;
  pathEfficiency: number | null;
} {
  if (state.outboundIntegrityBroken) return { normalizedPathLength: null, pathEfficiency: null };
  if (state.movementOnsetAtMs === null || state.movementOnsetWristPoint === null || state.targetEntryAtMs === null) {
    return { normalizedPathLength: null, pathEfficiency: null };
  }
  const samples = state.outboundSamples;
  if (samples.length < 2) return { normalizedPathLength: null, pathEfficiency: null };

  let length = 0;
  for (let i = 1; i < samples.length; i += 1) {
    length += distanceNormalized(samples[i - 1], samples[i]);
  }
  if (!Number.isFinite(length) || length <= 0) {
    return { normalizedPathLength: Number.isFinite(length) ? length : null, pathEfficiency: null };
  }

  const straightLineDistance = distanceNormalized(state.movementOnsetWristPoint, state.config.fixedTarget.point);
  const rawEfficiency = straightLineDistance / length;
  if (!Number.isFinite(rawEfficiency)) return { normalizedPathLength: length, pathEfficiency: null };

  if (rawEfficiency > 1 + PATH_EFFICIENCY_TOLERANCE || rawEfficiency < 0 - PATH_EFFICIENCY_TOLERANCE) {
    return { normalizedPathLength: length, pathEfficiency: null };
  }
  const efficiency = Math.min(1, Math.max(0, rawEfficiency));
  return { normalizedPathLength: length, pathEfficiency: efficiency };
}

function trackingQualitySummary(): "unknown" {
  return "unknown";
}

const FACTUAL_NOTE_OBSERVED_2D_ELBOW_ANGLE_DATA_AVAILABLE = "observed_2d_elbow_angle_data_available";
const FACTUAL_NOTE_OBSERVED_2D_ELBOW_ANGLE_DATA_UNAVAILABLE =
  "observed_2d_elbow_angle_data_unavailable:required_landmarks_not_sufficiently_tracked";

function buildFactualNotes(state: ElbowExtensionAttemptStateInternal): string[] {
  const notes: string[] = [];
  if (state.protectivePauseEvents.length > 0) {
    notes.push(`protective_pause_count:${state.protectivePauseEvents.length}`);
  }
  if (state.runtimeInterruptionOccurred) notes.push("runtime_interruption_received");
  if (state.notAssessableReason) notes.push(`marked_not_assessable_reason:${state.notAssessableReason}`);
  if (state.nonTargetFacingExitObservedBeforeValidOnset) {
    notes.push("non_target_facing_exit_observed_before_valid_onset");
  }

  if (state.movementOnsetAtMs !== null) {
    if (state.hadValidElbowAngleSample && state.peakElbowExtensionDegRunning !== null) {
      notes.push(FACTUAL_NOTE_OBSERVED_2D_ELBOW_ANGLE_DATA_AVAILABLE);
    } else {
      notes.push(FACTUAL_NOTE_OBSERVED_2D_ELBOW_ANGLE_DATA_UNAVAILABLE);
    }
  }

  return notes;
}

function sumProtectivePauseDurationMs(events: readonly ProtectivePauseEvent[]): number {
  let total = 0;
  for (const event of events) {
    const duration = event.endedAtMs !== null ? event.endedAtMs - event.startedAtMs : 0;
    if (duration < 0) {
      throw new Error("elbow-extension-engine: internal inconsistency — a finalized pause has a negative duration");
    }
    total += duration;
  }
  return total;
}

function buildAttemptResult(
  state: ElbowExtensionAttemptStateInternal,
  completionState: UpperLimbAttemptCompletionState,
  completedAtMs: number,
): UpperLimbMovementAttemptResult {
  const hasClinicalStop = state.clinicalStopEvent !== null;
  const hasRuntimeInterruption = state.runtimeInterruptionOccurred;
  if (!isCompletionStateConsistentWithEvents({ completionState, hasClinicalStop, hasRuntimeInterruption })) {
    throw new Error(
      `elbow-extension-engine: internal inconsistency — completionState "${completionState}" is not consistent with recorded events`,
    );
  }

  const reachTimeMs =
    state.targetEntryAtMs !== null && state.movementOnsetAtMs !== null
      ? state.targetEntryAtMs - state.movementOnsetAtMs
      : null;
  const returnTimeMs =
    state.returnConfirmedAtMs !== null && state.reachConfirmedAtMs !== null
      ? state.returnConfirmedAtMs - state.reachConfirmedAtMs
      : null;
  const totalMovementTimeMs = state.movementOnsetAtMs !== null ? completedAtMs - state.movementOnsetAtMs : null;

  for (const [label, value] of [
    ["reachTimeMs", reachTimeMs],
    ["returnTimeMs", returnTimeMs],
    ["totalMovementTimeMs", totalMovementTimeMs],
  ] as const) {
    if (value !== null && value < 0) {
      throw new Error(`elbow-extension-engine: internal inconsistency — ${label} computed as negative (${value})`);
    }
  }

  const pathMetrics = computePathMetrics(state);
  const protectivePauseDurationMs = sumProtectivePauseDurationMs(state.protectivePauseEvents);

  if (state.targetReachedFlag !== state.dwellConfirmedFlag) {
    throw new Error(
      "elbow-extension-engine: internal inconsistency — targetReached and dwellConfirmed diverged; targetReached means dwell-confirmed entry only",
    );
  }

  const peakElbowExtensionDeg =
    state.hadValidElbowAngleSample && state.peakElbowExtensionDegRunning !== null
      ? state.peakElbowExtensionDegRunning
      : null;

  const result: UpperLimbMovementAttemptResult = {
    attemptIndex: state.attemptIndex,
    taskId: "elbowExtension",
    testedSide: state.config.testedSide,
    startedAtMs: state.armedAtMs,
    completedAtMs,
    completionState,

    targetReached: state.targetReachedFlag,
    dwellConfirmed: state.dwellConfirmedFlag,
    returnToStartCompleted: state.returnToStartCompletedFlag,

    reachTimeMs,
    returnTimeMs,
    totalMovementTimeMs,
    normalizedPathLength: pathMetrics.normalizedPathLength,
    pathEfficiency: pathMetrics.pathEfficiency,
    peakShoulderAngleDeg: null,
    peakElbowExtensionDeg,

    trunkDisplacementObserved: null,
    withinConfiguredLimitThroughout: null,

    trackingQualitySummary: trackingQualitySummary(),
    protectivePauseCount: state.protectivePauseEvents.length,
    protectivePauseDurationMs,
    protectivePauseEvents: [...state.protectivePauseEvents],

    factualNotes: buildFactualNotes(state),
  };

  const safety = validateUpperLimbMotorScreenSessionResultSafety(result);
  if (!safety.ok) {
    throw new Error(
      `elbow-extension-engine: internal inconsistency — finalized result failed the safety-vocabulary check at ${safety.forbiddenKeyPaths.join(", ")}`,
    );
  }

  return result;
}

type FinalizeOutcome = "completed" | "incomplete" | "interrupted" | "stopped" | "not_assessable" | "not_started";

function finalizeAttempt(
  state: ElbowExtensionAttemptStateInternal,
  nowMs: number,
  completionState: FinalizeOutcome,
  pauseOutcomeIfActive: "escalated_to_clinical_stop" | "session_ended_while_paused",
): ElbowExtensionCommandResult {
  let next = state;
  let finalizedPauseEvent: ProtectivePauseEvent | null = null;

  if (next.activePause) {
    const evaluation = evaluateProtectivePause({
      reason: next.activePause.reason,
      startedAtMs: next.activePause.startedAtMs,
      endedAtMs: nowMs,
      outcome: pauseOutcomeIfActive,
      readinessConfirmedAt: null,
      resumedBy: null,
    });
    if (!evaluation.ok) {
      throw new Error(
        `elbow-extension-engine: internal inconsistency — evaluateProtectivePause rejected an engine-constructed pause finalization (${evaluation.reason})`,
      );
    }
    finalizedPauseEvent = evaluation.event;
    next = {
      ...next,
      activePause: null,
      protectivePauseEvents: [...next.protectivePauseEvents, evaluation.event],
    };
  }

  const result = buildAttemptResult(next, completionState, nowMs);
  next = { ...next, terminal: true, completedAtMs: nowMs, finalResult: result };
  return applied(next, finalizedPauseEvent, result);
}

function resetContinuityCandidates(state: ElbowExtensionAttemptStateInternal): ElbowExtensionAttemptStateInternal {
  const revertedPhase: ElbowExtensionPhase = state.phase === "dwelling" ? "outbound" : state.phase;
  const outboundIntegrityBroken =
    state.outboundIntegrityBroken || (revertedPhase === "outbound" && state.targetEntryAtMs === null);
  return {
    ...state,
    phase: revertedPhase,
    onsetCandidate: null,
    pendingOnsetSamples: [],
    pendingTargetEntryAtMs: null,
    dwellCandidate: null,
    returnCandidate: null,
    outboundIntegrityBroken,
  };
}

function confirmMovementOnset(
  state: ElbowExtensionAttemptStateInternal,
  candidateStartedAtMs: number,
  pendingSamples: NormalizedPoint[],
  nowMs: number,
  sample: NormalizedPoint,
  frame: NormalizedMotionFrame,
): ElbowExtensionCommandResult {
  const onsetPoint = pendingSamples[0];
  const pendingTargetEntryAtMs = state.pendingTargetEntryAtMs;
  const insideTarget = isWristInsideTarget(sample, state.config.fixedTarget.point, {
    collisionRadius: state.config.fixedTarget.radius,
  });
  const targetEntryAtMs = pendingTargetEntryAtMs ?? (insideTarget ? nowMs : null);

  let next: ElbowExtensionAttemptStateInternal = {
    ...state,
    phase: "outbound",
    onsetCandidate: null,
    pendingOnsetSamples: [],
    pendingTargetEntryAtMs: null,
    movementOnsetAtMs: candidateStartedAtMs,
    movementOnsetWristPoint: onsetPoint,
    outboundSamples: pendingSamples,
  };

  next = observePeakElbowAngleIfApplicable(next, frame);

  if (targetEntryAtMs !== null && insideTarget) {
    const outboundSamples = pendingSamples;
    const candidate: DwellCandidate = {
      candidateStartedAtMs: targetEntryAtMs,
      outboundSamplesAtEntry: outboundSamples,
    };
    const elapsed = nowMs - candidate.candidateStartedAtMs;
    if (elapsed >= state.config.timing.dwellDurationMs) {
      next = observePeakElbowAngleIfApplicable(next, frame);
      return applied({
        ...next,
        phase: "reach_confirmed",
        dwellCandidate: null,
        targetEntryAtMs: candidate.candidateStartedAtMs,
        targetReachedFlag: true,
        dwellConfirmedFlag: true,
        reachConfirmedAtMs: nowMs,
        outboundSamples: candidate.outboundSamplesAtEntry,
      });
    }
    return applied({ ...next, phase: "dwelling", outboundSamples, dwellCandidate: candidate });
  }

  return applied(next);
}

function handleReadyConfirmedAwaitingOnset(
  state: ElbowExtensionAttemptStateInternal,
  sample: NormalizedPoint,
  frame: NormalizedMotionFrame,
  nowMs: number,
): ElbowExtensionCommandResult {
  const { startingZone, fixedTarget, normalizedTargetDirection, timing } = state.config;

  const insideStartingZone = isWristInsideTarget(sample, startingZone.point, {
    collisionRadius: startingZone.radius,
  });
  if (insideStartingZone) {
    return applied({
      ...state,
      onsetCandidate: null,
      pendingOnsetSamples: [],
      pendingTargetEntryAtMs: null,
    });
  }

  if (hasWrongDirectionExit(sample, startingZone, normalizedTargetDirection)) {
    return applied({
      ...state,
      phase: "awaiting_readiness",
      onsetCandidate: null,
      pendingOnsetSamples: [],
      pendingTargetEntryAtMs: null,
      nonTargetFacingExitObservedBeforeValidOnset: true,
    });
  }

  const insideTarget = isWristInsideTarget(sample, fixedTarget.point, {
    collisionRadius: fixedTarget.radius,
  });
  const pendingTargetEntryAtMs =
    insideTarget && state.pendingTargetEntryAtMs === null ? nowMs : state.pendingTargetEntryAtMs;

  if (!hasTargetFacingOnsetQualification(sample, startingZone, normalizedTargetDirection)) {
    return applied({
      ...state,
      pendingTargetEntryAtMs,
      onsetCandidate: null,
      pendingOnsetSamples: [],
    });
  }

  const candidate = state.onsetCandidate ?? { candidateStartedAtMs: nowMs };
  const pendingSamples =
    state.onsetCandidate === null ? [sample] : [...state.pendingOnsetSamples, sample];
  const elapsed = nowMs - candidate.candidateStartedAtMs;

  if (elapsed >= timing.onsetConfirmationMs) {
    return confirmMovementOnset(
      { ...state, pendingTargetEntryAtMs },
      candidate.candidateStartedAtMs,
      pendingSamples,
      nowMs,
      sample,
      frame,
    );
  }

  return applied({
    ...state,
    onsetCandidate: candidate,
    pendingOnsetSamples: pendingSamples,
    pendingTargetEntryAtMs,
  });
}

function handleOutboundOrDwelling(
  state: ElbowExtensionAttemptStateInternal,
  sample: NormalizedPoint,
  frame: NormalizedMotionFrame,
  nowMs: number,
): ElbowExtensionCommandResult {
  const next = observePeakElbowAngleIfApplicable(state, frame);

  const outboundSamples = [...next.outboundSamples, sample];
  const insideTarget = isWristInsideTarget(sample, next.config.fixedTarget.point, {
    collisionRadius: next.config.fixedTarget.radius,
  });

  if (!insideTarget) {
    return applied({ ...next, phase: "outbound", outboundSamples, dwellCandidate: null });
  }

  const candidate: DwellCandidate =
    next.dwellCandidate ?? { candidateStartedAtMs: nowMs, outboundSamplesAtEntry: outboundSamples };
  const elapsed = nowMs - candidate.candidateStartedAtMs;

  if (elapsed >= next.config.timing.dwellDurationMs) {
    return applied({
      ...next,
      phase: "reach_confirmed",
      dwellCandidate: null,
      targetEntryAtMs: candidate.candidateStartedAtMs,
      targetReachedFlag: true,
      dwellConfirmedFlag: true,
      reachConfirmedAtMs: nowMs,
      outboundSamples: candidate.outboundSamplesAtEntry,
    });
  }

  return applied({ ...next, phase: "dwelling", outboundSamples, dwellCandidate: candidate });
}

// ---------------------------------------------------------------------------
// Tracking-loss handling — shared by frame with invalid wrist and observationUnavailable
// ---------------------------------------------------------------------------

/**
 * Applies tracking-loss semantics when no usable wrist observation is available.
 * Used by both frame commands with invalid/missing wrist and observationUnavailable commands.
 */
function handleInvalidTracking(
  state: ElbowExtensionAttemptStateInternal,
  nowMs: number,
): ElbowExtensionCommandResult {
  const invalidSince = state.invalidTrackingSinceMs ?? nowMs;
  let next = resetContinuityCandidates({ ...state, invalidTrackingSinceMs: invalidSince });

  const gapDurationMs = nowMs - invalidSince;
  if (
    gapDurationMs >= next.config.tracking.maxAllowedGapMs &&
    next.activePause === null &&
    next.phase !== "completed_pending_finalization"
  ) {
    next = {
      ...next,
      activePause: {
        reason: { category: "tracking_or_environment", detail: "wrist_landmark_lost" },
        startedAtMs: invalidSince,
      },
    };
  }
  return applied(next);
}

function handleFrame(
  state: ElbowExtensionAttemptStateInternal,
  nowMs: number,
  frame: NormalizedMotionFrame,
): ElbowExtensionCommandResult {
  let next = state.phase === "idle" ? { ...state, phase: "awaiting_readiness" as ElbowExtensionPhase } : { ...state };

  const sample = extractTestedSideWristSample(frame, next.config);

  if (sample === null) {
    return handleInvalidTracking(next, nowMs);
  }

  next = { ...next, lastValidWristSample: { point: sample, atMs: nowMs }, invalidTrackingSinceMs: null };

  if (next.activePause !== null) {
    return applied(next);
  }

  switch (next.phase) {
    case "awaiting_readiness":
      return applied(next);

    case "ready_confirmed_awaiting_onset":
      return handleReadyConfirmedAwaitingOnset(next, sample, frame, nowMs);

    case "outbound":
    case "dwelling":
      return handleOutboundOrDwelling(next, sample, frame, nowMs);

    case "reach_confirmed":
    case "returning": {
      const promoted = next.phase === "reach_confirmed" ? { ...next, phase: "returning" as ElbowExtensionPhase } : next;
      const insideStartingZone = isWristInsideTarget(sample, promoted.config.startingZone.point, {
        collisionRadius: promoted.config.startingZone.radius,
      });
      if (!insideStartingZone) {
        return applied({ ...promoted, returnCandidate: null });
      }
      const candidate = promoted.returnCandidate ?? { candidateStartedAtMs: nowMs };
      const elapsed = nowMs - candidate.candidateStartedAtMs;
      if (elapsed >= promoted.config.timing.returnConfirmationMs) {
        return applied({
          ...promoted,
          phase: "completed_pending_finalization",
          returnCandidate: null,
          returnConfirmedAtMs: nowMs,
          returnToStartCompletedFlag: true,
        });
      }
      return applied({ ...promoted, returnCandidate: candidate });
    }

    case "completed_pending_finalization":
      return applied(next);

    case "idle":
      return applied(next);

    default: {
      const _exhaustive: never = next.phase;
      return _exhaustive;
    }
  }
}

export function applyElbowExtensionCommand(
  state: ElbowExtensionAttemptState,
  command: ElbowExtensionCommand,
): ElbowExtensionCommandResult {
  if (state.terminal) {
    return rejected(state, "attempt_already_terminal");
  }

  const clockCheck = validateNowMs(state.lastAcceptedNowMs, command.nowMs);
  if (!clockCheck.ok) {
    return rejected(state, clockCheck.reason);
  }

  // Movement-observation commands (frame, observationUnavailable) must not
  // mutate a completed attempt awaiting finalization.
  if (
    (command.type === "frame" || command.type === "observationUnavailable") &&
    state.phase === "completed_pending_finalization"
  ) {
    return rejected(state, "awaiting_explicit_finalization");
  }

  if (command.type === "frame") {
    const frameClockCheck = validateFrameNowMs(state.lastAcceptedFrameNowMs, command.nowMs);
    if (!frameClockCheck.ok) {
      return rejected(state, frameClockCheck.reason);
    }
  }

  const stateWithClock: ElbowExtensionAttemptStateInternal = {
    ...state,
    lastAcceptedNowMs: command.nowMs,
    ...(command.type === "frame" ? { lastAcceptedFrameNowMs: command.nowMs } : {}),
  };

  switch (command.type) {
    case "frame":
      return handleFrame(stateWithClock, command.nowMs, command.frame);

    case "observationUnavailable": {
      const next = stateWithClock.phase === "idle" ? { ...stateWithClock, phase: "awaiting_readiness" as ElbowExtensionPhase } : { ...stateWithClock };
      return handleInvalidTracking(next, command.nowMs);
    }

    case "readinessConfirmed": {
      if (stateWithClock.phase !== "idle" && stateWithClock.phase !== "awaiting_readiness") {
        return rejected(stateWithClock, "readiness_not_applicable_in_current_phase");
      }
      if (!isValidProtectivePauseResumeActor(command.confirmedBy)) {
        return rejected(stateWithClock, "readiness_requires_valid_confirmed_by");
      }
      const wristSample = stateWithClock.lastValidWristSample;
      if (wristSample === null || command.nowMs - wristSample.atMs > stateWithClock.config.tracking.maxAllowedGapMs) {
        return rejected(stateWithClock, "readiness_requires_wrist_in_starting_zone");
      }
      const inZone = isWristInsideTarget(wristSample.point, stateWithClock.config.startingZone.point, {
        collisionRadius: stateWithClock.config.startingZone.radius,
      });
      if (!inZone) {
        return rejected(stateWithClock, "readiness_requires_wrist_in_starting_zone");
      }
      return applied({ ...stateWithClock, phase: "ready_confirmed_awaiting_onset" });
    }

    case "resumeRequested": {
      if (!stateWithClock.activePause) {
        return rejected(stateWithClock, "no_active_pause_to_resume");
      }
      const readinessConfirmedAt =
        typeof command.readinessConfirmedAt === "string" ? command.readinessConfirmedAt : null;
      const evaluation = evaluateProtectivePause({
        reason: stateWithClock.activePause.reason,
        startedAtMs: stateWithClock.activePause.startedAtMs,
        endedAtMs: command.nowMs,
        outcome: "resumed",
        readinessConfirmedAt,
        resumedBy: command.resumedBy,
      });
      if (!evaluation.ok) {
        if (evaluation.reason === "readiness_confirmation_required_for_resume") {
          return rejected(stateWithClock, "resume_requires_readiness_confirmation");
        }
        return rejected(stateWithClock, "resume_requires_valid_human_actor");
      }
      return applied(
        {
          ...stateWithClock,
          activePause: null,
          invalidTrackingSinceMs: null,
          protectivePauseEvents: [...stateWithClock.protectivePauseEvents, evaluation.event],
        },
        evaluation.event,
      );
    }

    case "clinicalStopReceived": {
      const next = { ...stateWithClock, clinicalStopEvent: { ...command.event } };
      return finalizeAttempt(next, command.nowMs, "stopped", "escalated_to_clinical_stop");
    }

    case "runtimeInterruptionReceived": {
      const next = { ...stateWithClock, runtimeInterruptionOccurred: true };
      return finalizeAttempt(next, command.nowMs, "interrupted", "session_ended_while_paused");
    }

    case "markedNotAssessable": {
      const next = { ...stateWithClock, notAssessableReason: command.reason };
      return finalizeAttempt(next, command.nowMs, "not_assessable", "session_ended_while_paused");
    }

    case "attemptWindowEnded": {
      if (stateWithClock.activePause) {
        return finalizeAttempt(stateWithClock, command.nowMs, "not_assessable", "session_ended_while_paused");
      }
      if (stateWithClock.phase === "completed_pending_finalization") {
        return finalizeAttempt(stateWithClock, command.nowMs, "completed", "session_ended_while_paused");
      }
      if (stateWithClock.movementOnsetAtMs === null) {
        return finalizeAttempt(stateWithClock, command.nowMs, "not_started", "session_ended_while_paused");
      }
      return finalizeAttempt(stateWithClock, command.nowMs, "incomplete", "session_ended_while_paused");
    }

    default: {
      const _exhaustive: never = command;
      return _exhaustive;
    }
  }
}
