-- ============================================================
-- Migration 019 — upper_limb_motor_screen_assignments,
--                  upper_limb_motor_screen_session_results
--
-- Schema-only persistence boundary for the Upper-Limb Motor Screen
-- domain (app/lib/upper-limb-motor-screen/). No API route, no
-- repository/mapper code, no TypeScript changes accompany this
-- migration — those are deferred to a later slice.
--
-- Assignment must exist before a session result can reference it, so
-- upper_limb_motor_screen_assignments is created first.
--
-- Ownership: real Supabase UUID patients/providers only. patient_id
-- and provider_id are NOT NULL on both tables — numeric/legacy demo
-- patients (localStorage-only, never a public.patients row) are not
-- supported by this persistence layer, by design.
--
-- Identity: id is never database-generated on either table (no
-- default). The future server-side persistence boundary must generate
-- the UUID (e.g. via crypto.randomUUID()) before constructing the
-- domain snapshot, and use that exact same value as both the domain
-- object's own id field and the row's primary key — never two
-- different UUIDs for one record, and never generated by the browser.
--
-- Canonical payload: assignment_payload / result_payload each hold
-- the complete, unmodified domain object as JSONB (semantic/structural
-- preservation of every field — JSONB does not preserve byte
-- representation, key order, or whitespace, and nothing here depends
-- on it doing so). Typed columns are read-optimization projections of
-- fields already stable, query-relevant, and semantically defined;
-- they are never an independent source of truth. Fields with
-- unresolved semantics (e.g. longestPauseGapMs) or unresolved
-- multi-attempt/aggregation policy (taskCompletion, attempts,
-- interruptions.*, observedMovementFeatures.*) intentionally have no
-- column here at all and live only inside the JSONB payload.
--
-- Naming note: constraint/policy identifiers on
-- upper_limb_motor_screen_session_results (and a few on
-- upper_limb_motor_screen_assignments) use the short prefixes
-- "ulmsa"/"ulmssr" instead of the full table name, because PostgreSQL
-- identifiers are limited to 63 bytes and the full table names are
-- already 36/40 characters — a fully-prefixed constraint name would
-- silently truncate and risk collisions. Index and trigger names keep
-- the full table-name prefix, which fits.
--
-- Prerequisites:
--   - 000_schema_baseline.sql (patients)
--   - 001_providers.sql (providers, public.set_updated_at())
-- ============================================================

-- ------------------------------------------------------------
-- 1. upper_limb_motor_screen_assignments
-- ------------------------------------------------------------

create table if not exists public.upper_limb_motor_screen_assignments (
  -- No database default: the persistence boundary must supply this
  -- UUID explicitly (see the Identity note above) — assignment_payload.id
  -- must already equal id (ulmsa_payload_id_chk below), which a
  -- DB-generated default could never satisfy.
  id                  uuid        primary key,
  provider_id         uuid        not null references public.providers(id) on delete restrict,
  patient_id          uuid        not null references public.patients(id) on delete restrict,
  status              text        not null,
  assignment_payload  jsonb       not null,
  schema_version      text        not null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint ulmsa_status_chk
    check (status in ('assigned', 'started', 'completed', 'cancelled')),

  -- Consistency between the canonical payload and its typed projections.
  -- IS NOT DISTINCT FROM (not =) so a missing/null payload key is
  -- treated as a genuine mismatch and rejected, rather than passing
  -- CHECK by way of NULL = anything evaluating to NULL (which Postgres
  -- treats as satisfied, not violated).
  constraint ulmsa_payload_id_chk
    check ((assignment_payload->>'id') is not distinct from id::text),

  constraint ulmsa_payload_status_chk
    check ((assignment_payload->>'status') is not distinct from status),

  -- Backs the composite ownership FK from upper_limb_motor_screen_session_results.
  constraint ulmsa_id_provider_patient_key
    unique (id, provider_id, patient_id)
);

create index if not exists upper_limb_motor_screen_assignments_provider_id_idx
  on public.upper_limb_motor_screen_assignments (provider_id);

create index if not exists upper_limb_motor_screen_assignments_patient_id_idx
  on public.upper_limb_motor_screen_assignments (patient_id);

create index if not exists upper_limb_motor_screen_assignments_status_idx
  on public.upper_limb_motor_screen_assignments (status);

alter table public.upper_limb_motor_screen_assignments enable row level security;

create policy "upper_limb_motor_screen_assignments: provider selects own"
  on public.upper_limb_motor_screen_assignments for select
  using (provider_id = auth.uid());

create policy "upper_limb_motor_screen_assignments: provider inserts own"
  on public.upper_limb_motor_screen_assignments for insert
  with check (provider_id = auth.uid());

create policy "upper_limb_motor_screen_assignments: provider updates own"
  on public.upper_limb_motor_screen_assignments for update
  using (provider_id = auth.uid())
  with check (provider_id = auth.uid());

create policy "upper_limb_motor_screen_assignments: provider deletes own"
  on public.upper_limb_motor_screen_assignments for delete
  using (provider_id = auth.uid());

-- Status / assignment_payload / schema_version remain fully mutable per
-- future workflow — no assignment lifecycle rule is invented here.
-- Identity/ownership must not silently change, on every update.
drop trigger if exists upper_limb_motor_screen_assignments_set_updated_at
  on public.upper_limb_motor_screen_assignments;
create trigger upper_limb_motor_screen_assignments_set_updated_at
  before update on public.upper_limb_motor_screen_assignments
  for each row execute function public.set_updated_at();

create or replace function public.enforce_ul_assignment_identity_immutability()
returns trigger language plpgsql as $$
begin
  if new.id is distinct from old.id
     or new.provider_id is distinct from old.provider_id
     or new.patient_id is distinct from old.patient_id
     or new.created_at is distinct from old.created_at
  then
    raise exception
      'upper_limb_motor_screen_assignments: identity/ownership fields are immutable for row %', old.id;
  end if;

  return new;
end;
$$;

drop trigger if exists upper_limb_motor_screen_assignments_identity_immutability
  on public.upper_limb_motor_screen_assignments;
create trigger upper_limb_motor_screen_assignments_identity_immutability
  before update on public.upper_limb_motor_screen_assignments
  for each row execute function public.enforce_ul_assignment_identity_immutability();

grant select, insert, update, delete
  on public.upper_limb_motor_screen_assignments to service_role;

-- ------------------------------------------------------------
-- 2. upper_limb_motor_screen_session_results
-- ------------------------------------------------------------

create table if not exists public.upper_limb_motor_screen_session_results (
  -- No database default: see the Identity note above and the
  -- equivalent id column on upper_limb_motor_screen_assignments.
  -- result_payload.id must already equal id (ulmssr_payload_id_chk
  -- below), which a DB-generated default could never satisfy.
  id                                  uuid        primary key,
  -- No standalone FK to upper_limb_motor_screen_assignments(id): the
  -- composite ownership FK below already requires assignment_id to
  -- resolve to a real assignments row, and additionally pins
  -- provider_id/patient_id to that same row's own values — a separate
  -- single-column FK here would be redundant, not protective.
  assignment_id                       uuid        not null,
  -- Denormalized from the parent assignment at creation (matches the
  -- plan_sessions / session_logs precedent, avoiding an RLS join).
  provider_id                         uuid        not null,
  patient_id                          uuid        not null,
  status                              text        not null default 'computed',
  result_payload                      jsonb       not null,
  overall_quality                     text        not null,
  protective_pause_count              integer     not null,
  protective_pause_duration_ms_total  integer     not null,
  schema_version                      text        not null,
  created_at                          timestamptz not null default now(),
  updated_at                          timestamptz not null default now(),

  constraint ulmssr_status_chk
    check (status in ('computed', 'finalized')),

  constraint ulmssr_overall_quality_chk
    check (overall_quality in ('good', 'fair', 'poor', 'unknown')),

  -- Payload/typed-projection consistency — IS NOT DISTINCT FROM, same
  -- NULL-passthrough reasoning as the assignments table above.
  constraint ulmssr_payload_id_chk
    check ((result_payload->>'id') is not distinct from id::text),

  constraint ulmssr_payload_assignment_id_chk
    check ((result_payload->>'assignmentId') is not distinct from assignment_id::text),

  constraint ulmssr_payload_status_chk
    check ((result_payload->>'status') is not distinct from status),

  constraint ulmssr_payload_overall_quality_chk
    check (
      (result_payload->'technicalTrackingQuality'->>'overallQuality')
      is not distinct from overall_quality
    ),

  constraint ulmssr_payload_pause_count_chk
    check (
      (result_payload->'technicalTrackingQuality'->>'protectivePauseCount')::integer
      is not distinct from protective_pause_count
    ),

  constraint ulmssr_payload_pause_duration_chk
    check (
      (result_payload->'technicalTrackingQuality'->>'protectivePauseDurationMsTotal')::integer
      is not distinct from protective_pause_duration_ms_total
    ),

  -- Structural guarantee that a session result cannot reference
  -- assignment A while carrying a provider_id/patient_id that differs
  -- from assignment A's own values — enforced by the database, not
  -- application code. Requires ulmsa_id_provider_patient_key above.
  -- on update restrict: an assignment's provider_id/patient_id should
  -- never silently cascade an ownership change onto referencing
  -- session results; that must fail loudly instead.
  constraint ulmssr_assignment_ownership_fkey
    foreign key (assignment_id, provider_id, patient_id)
    references public.upper_limb_motor_screen_assignments (id, provider_id, patient_id)
    on delete restrict
    on update restrict
);

create index if not exists upper_limb_motor_screen_session_results_assignment_id_idx
  on public.upper_limb_motor_screen_session_results (assignment_id);

create index if not exists upper_limb_motor_screen_session_results_provider_id_idx
  on public.upper_limb_motor_screen_session_results (provider_id);

create index if not exists upper_limb_motor_screen_session_results_patient_id_idx
  on public.upper_limb_motor_screen_session_results (patient_id);

create index if not exists upper_limb_motor_screen_session_results_status_idx
  on public.upper_limb_motor_screen_session_results (status);

-- No unique constraint on assignment_id: whether one assignment may
-- have multiple session results is unresolved policy, not decided by
-- this migration.

alter table public.upper_limb_motor_screen_session_results enable row level security;

create policy "ulmssr: provider selects own"
  on public.upper_limb_motor_screen_session_results for select
  using (provider_id = auth.uid());

-- Every new row must begin as computed — a finalized row can never be
-- inserted directly. Reinforced, for every role including
-- service_role, by the trigger below.
create policy "ulmssr: provider inserts computed rows"
  on public.upper_limb_motor_screen_session_results for insert
  with check (provider_id = auth.uid() and status = 'computed');

-- USING: only computed rows owned by the provider may be updated.
-- WITH CHECK: the new row must remain provider-owned and land on
-- computed or finalized only. A finalized row no longer satisfies
-- USING, so no further authenticated-session UPDATE can reach it —
-- reinforced, for every role including service_role, by the trigger
-- below.
create policy "ulmssr: provider updates computed rows"
  on public.upper_limb_motor_screen_session_results for update
  using (provider_id = auth.uid() and status = 'computed')
  with check (provider_id = auth.uid() and status in ('computed', 'finalized'));

-- Computed-row deletion remains allowed via the authenticated provider
-- path; finalized rows are not deletable this way. See the trigger
-- below for the service_role-inclusive enforcement.
create policy "ulmssr: provider deletes computed rows"
  on public.upper_limb_motor_screen_session_results for delete
  using (provider_id = auth.uid() and status = 'computed');

drop trigger if exists upper_limb_motor_screen_session_results_set_updated_at
  on public.upper_limb_motor_screen_session_results;
create trigger upper_limb_motor_screen_session_results_set_updated_at
  before update on public.upper_limb_motor_screen_session_results
  for each row execute function public.set_updated_at();

-- Defense in depth against the service_role bypass, which RLS cannot
-- reach: this trigger fires for every role.
--
--   - Every INSERT must land with status = 'computed' — a finalized
--     row can never be created directly, for any role. Rejected
--     outright (not silently rewritten to computed) if violated. The
--     existing ulmssr_payload_status_chk CHECK independently requires
--     result_payload.status = 'computed' too, since it is evaluated
--     against the same NEW.status this branch has already confirmed.
--   - Any UPDATE or DELETE on an already-finalized row is rejected
--     outright.
--   - On every UPDATE while still computed (computed->computed and
--     computed->finalized alike): id/assignment_id/provider_id/
--     patient_id/created_at are immutable. "Computed rows are freely
--     overwritable" applies to content, never to record identity or
--     ownership.
--   - On computed->finalized specifically: result_payload content
--     other than the top-level status key, and every typed
--     projection/schema_version, must be unchanged — finalize is a
--     pure status flip, never a simultaneous content edit.
--   - The payload's own status key is synchronized here
--     (jsonb_set(...)) so the caller only needs to flip the row's
--     status column, not resend the entire snapshot; the existing
--     ulmssr_payload_status_chk CHECK constraint is evaluated against
--     this trigger's finished NEW row (standard, well-defined
--     BEFORE-trigger-then-CHECK ordering), so it is satisfied by
--     construction.
create or replace function public.enforce_ul_session_result_immutability()
returns trigger language plpgsql as $$
declare
  submitted_payload jsonb;
begin
  if tg_op = 'INSERT' then
    if new.status <> 'computed' then
      raise exception
        'upper_limb_motor_screen_session_results: new rows must begin as computed (got status %)', new.status;
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    if old.status = 'finalized' then
      raise exception
        'upper_limb_motor_screen_session_results: row % is finalized and cannot be deleted', old.id;
    end if;
    return old;
  end if;

  -- tg_op = 'UPDATE' below.
  if old.status = 'finalized' then
    raise exception
      'upper_limb_motor_screen_session_results: row % is finalized and immutable', old.id;
  end if;

  -- old.status = 'computed' here (the only other legal value).
  if new.id is distinct from old.id
     or new.assignment_id is distinct from old.assignment_id
     or new.provider_id is distinct from old.provider_id
     or new.patient_id is distinct from old.patient_id
     or new.created_at is distinct from old.created_at
  then
    raise exception
      'upper_limb_motor_screen_session_results: identity/ownership fields are immutable for row %', old.id;
  end if;

  if new.status = 'finalized' then
    -- Capture what the caller actually submitted before this trigger
    -- rewrites result_payload below, so the "no content change besides
    -- status" check is not silently short-circuited by our own rewrite.
    submitted_payload := new.result_payload;

    if (submitted_payload - 'status') is distinct from (old.result_payload - 'status') then
      raise exception
        'upper_limb_motor_screen_session_results: cannot change result_payload content other than status while finalizing row %', old.id;
    end if;

    if new.overall_quality is distinct from old.overall_quality
       or new.protective_pause_count is distinct from old.protective_pause_count
       or new.protective_pause_duration_ms_total is distinct from old.protective_pause_duration_ms_total
       or new.schema_version is distinct from old.schema_version
    then
      raise exception
        'upper_limb_motor_screen_session_results: cannot change typed projection fields while finalizing row %', old.id;
    end if;

    -- Atomic, DB-side canonicalization of the one field allowed to change.
    new.result_payload := jsonb_set(old.result_payload, '{status}', to_jsonb('finalized'::text), true);
  end if;

  return new;
end;
$$;

drop trigger if exists upper_limb_motor_screen_session_results_immutability
  on public.upper_limb_motor_screen_session_results;
create trigger upper_limb_motor_screen_session_results_immutability
  before insert or update or delete on public.upper_limb_motor_screen_session_results
  for each row execute function public.enforce_ul_session_result_immutability();

grant select, insert, update, delete
  on public.upper_limb_motor_screen_session_results to service_role;
